services:
  - type: web
    name: nomination-system
    runtime: node
    buildCommand: npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false        # set manually in Render dashboard
      - key: JWT_SECRET
        sync: false        # set manually in Render dashboard
      - key: GROQ_API_KEY
        sync: false        # set manually in Render dashboard
      - key: MONGO_TLS_ALLOW_INVALID_CERT
        value: false
